### ISSUE TITLE
release or tag?

### ISSUE THREAD

**Issue by justinmk** [indoorvivants/tree-sitter-smithy#4]
Would you be willing to tag and possibly cut a github release?

FYI, I've also suggested adding your parser to nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1347352190

If you are willing to send a PR to nvim-treesitter,

- here's an example to follow: https://github.com/nvim-treesitter/nvim-treesitter/pull/3833
- here's instructions: https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers
    - one difference: to contribute the parser, edit `parsers.lua` directly

Thanks!

**Comment by keynmol** [comment]
Howdy!

> Would you be willing to tag and possibly cut a github release?

Is there some tooling that needs it? I've operated under the assumption that nvim-treesitter just pulls the repo when asked, so versions are not very meaningful.

Not opposed to it, but it's not going to mean anything with regards to semver and such :)

> FYI, I've also suggested adding your parser to nvim-treesitter

Yep, it's on my TODO list.

**Comment by justinmk** [comment]
> Is there some tooling that needs it? I've operated under the assumption that nvim-treesitter just pulls the repo when asked, so versions are not very meaningful.

It helps give a signal to downstream that "this [commit] is reasonably working" as opposed to potentially half-broken :) nvim-treesitter definitely appreciates it, though it's not required.



> > FYI, I've also suggested adding your parser to nvim-treesitter
> 
> Yep, it's on my TODO list.

Nice, thanks!

**Comment by keynmol** [comment]
Tagged: https://github.com/indoorvivants/tree-sitter-smithy/releases/tag/v0.1.0

Adding to nvim-treesitter will be tracked in #5
