### ISSUE TITLE
add to nvim-treesitter

### ISSUE THREAD

**Issue by amaanq** [indoorvivants/tree-sitter-smithy#6]
I'm willing to maintain this so...could I be added as a member/editor? I maintain smali, thrift, and capnp currently :)

**Comment by amaanq** [comment]
ping @keynmol

**Comment by keynmol** [comment]
Hi @amaanq!

At this point this is very low maintenance, and I'm happy to maintain it for now.
If there will be traffic on this repository that I can't manage, I will sure revisit your kind offer :)

Also, for any other discussion on this, an existing issue can be used. https://github.com/indoorvivants/tree-sitter-smithy/issues/5
